# Generated by Django 4.1.1 on 2022-09-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategoriler'},
        ),
    ]
